<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JoinRpg.Common.WebInfrastructure" />
		<PackageReference Include="JoinRpg.Common.EntityFrameworkCore" />
		<PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" />
		<PackageReference Include="OpenIddict.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Bastilia.Rating.Domain\Bastilia.Rating.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <InternalsVisibleTo Include="Bastilia.Rating.Tests" />
	</ItemGroup>

</Project>
