<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JoinRpg.Client\JoinRpg.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JoinRpg.Common.PrimitiveTypes" />
    <PackageReference Include="JoinRpg.Common.PrimitiveTypes.SourceGenerator" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
